In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#pd.set_option("display.max_rows", 1000)
pd.set_option("display.max_columns", 100)

In [2]:
file_paths = {'in':'../../../data/prepared/activity_log.csv',
              'out':'../../../data/prepared/activity_log_prepared.csv'
             }

df = pd.read_csv(file_paths['in'])

# guarantee the timestamps are datetime objects
time_columns = ['start_time','end_time','ride_date']

for time_col in time_columns:
    df[time_col] = pd.to_datetime(df[time_col])

In [3]:
df.head()

,ride_id,ride_date,elapsed_time,distance,moving_time,max_speed,avg_speed,elevation_gain,elevation_loss,avg_power,calories,perceived_exertion,perceived_relative_effort,simple_exertion,start_time,end_time,row_count,segment_count,ride_elapsed_time,ride_moving_time,elapsed_distance,elapsed_ascent,elapsed_descent,elapsed_elevation,ride_avg_speed,ride_cruise_speed,ride_max_speed,training_window_id,ride_avg_power,ride_max_power,peak_20min_power
0,2975587283,2020-01-02 14:02:00,1642,8.49,1411,9.0,6.023033,19.557501,NaN,NaN,NaN,7.0,45.0,HARD,2020-01-02 14:02:58+00:00,2020-01-02 14:29:32+00:00,1352,5,1595,1352,5.266647,137.1458,138.7863,275.9321,14.045509,14.547075,20.107674,0,116.870855,5.520265e+02,124.782357
1,2992935347,2020-01-08 13:20:00,1728,8.42,1472,14.2,5.725408,46.301785,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-08 13:20:26+00:00,2020-01-08 13:49:06+00:00,1426,5,1721,1426,5.167961,215.2336,153.2227,368.4563,13.119808,14.154069,30.585623,0,122.304555,9.702958e+02,131.178797
2,2994399692,2020-01-08 22:08:00,1608,8.52,1481,11.4,5.756246,26.526310,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-08 22:08:17+00:00,2020-01-08 22:35:04+00:00,1423,7,1608,1423,5.257609,158.4723,219.4989,377.9712,13.339800,15.443823,25.544568,0,113.161863,1.299650e+03,126.461932
3,3248077156,2020-04-02 21:38:00,5143,10.36,2544,13.4,4.074764,72.450409,55.750401,NaN,NaN,5.0,45.0,NORMAL,2020-04-02 21:38:02+00:00,2020-04-02 23:03:45+00:00,2580,5,5144,2580,6.759676,329.4124,274.6197,604.0321,9.548413,13.495738,219.457474,1,402.495491,2.608934e+05,737.913342
4,3255473930,2020-04-04 17:23:00,9348,34.95,6356,14.4,5.498946,105.704369,106.103996,NaN,NaN,5.0,114.0,NORMAL,2020-04-04 17:23:43+00:00,2020-04-04 19:59:16+00:00,6416,12,9334,6416,22.730090,575.1593,576.4717,1151.6310,12.764180,14.009717,513.399434,1,2104.760010,3.328601e+06,121.068376

# 1. Convert Strava Columns

In [4]:
km2mi = 0.621371 # kilometers to miles
MpS2MPH = 2.23694 # meters per second to MPH
m2ft = 3.28084 # meters to feet

convert_dict = {'distance':km2mi,
                'max_speed':MpS2MPH,
                'avg_speed':MpS2MPH,
                'elevation_gain':m2ft,
                'elevation_loss':m2ft,
               }

In [5]:
for column in convert_dict.keys():
    df[column] = df[column] * convert_dict[column]

In [6]:
df.head()

,ride_id,ride_date,elapsed_time,distance,moving_time,max_speed,avg_speed,elevation_gain,elevation_loss,avg_power,calories,perceived_exertion,perceived_relative_effort,simple_exertion,start_time,end_time,row_count,segment_count,ride_elapsed_time,ride_moving_time,elapsed_distance,elapsed_ascent,elapsed_descent,elapsed_elevation,ride_avg_speed,ride_cruise_speed,ride_max_speed,training_window_id,ride_avg_power,ride_max_power,peak_20min_power
0,2975587283,2020-01-02 14:02:00,1642,5.275440,1411,20.132460,13.473164,64.165031,NaN,NaN,NaN,7.0,45.0,HARD,2020-01-02 14:02:58+00:00,2020-01-02 14:29:32+00:00,1352,5,1595,1352,5.266647,137.1458,138.7863,275.9321,14.045509,14.547075,20.107674,0,116.870855,5.520265e+02,124.782357
1,2992935347,2020-01-08 13:20:00,1728,5.231944,1472,31.764548,12.807393,151.908747,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-08 13:20:26+00:00,2020-01-08 13:49:06+00:00,1426,5,1721,1426,5.167961,215.2336,153.2227,368.4563,13.119808,14.154069,30.585623,0,122.304555,9.702958e+02,131.178797
2,2994399692,2020-01-08 22:08:00,1608,5.294081,1481,25.501115,12.876376,87.028579,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-08 22:08:17+00:00,2020-01-08 22:35:04+00:00,1423,7,1608,1423,5.257609,158.4723,219.4989,377.9712,13.339800,15.443823,25.544568,0,113.161863,1.299650e+03,126.461932
3,3248077156,2020-04-02 21:38:00,5143,6.437404,2544,29.974995,9.115003,237.698200,182.908144,NaN,NaN,5.0,45.0,NORMAL,2020-04-02 21:38:02+00:00,2020-04-02 23:03:45+00:00,2580,5,5144,2580,6.759676,329.4124,274.6197,604.0321,9.548413,13.495738,219.457474,1,402.495491,2.608934e+05,737.913342
4,3255473930,2020-04-04 17:23:00,9348,21.716916,6356,32.211935,12.300812,346.799121,348.110235,NaN,NaN,5.0,114.0,NORMAL,2020-04-04 17:23:43+00:00,2020-04-04 19:59:16+00:00,6416,12,9334,6416,22.730090,575.1593,576.4717,1151.6310,12.764180,14.009717,513.399434,1,2104.760010,3.328601e+06,121.068376

# 2. Re-order the Columns

In [7]:
df.columns

Index(['ride_id', 'ride_date', 'elapsed_time', 'distance', 'moving_time',
       'max_speed', 'avg_speed', 'elevation_gain', 'elevation_loss',
       'avg_power', 'calories', 'perceived_exertion',
       'perceived_relative_effort', 'simple_exertion', 'start_time',
       'end_time', 'row_count', 'segment_count', 'ride_elapsed_time',
       'ride_moving_time', 'elapsed_distance', 'elapsed_ascent',
       'elapsed_descent', 'elapsed_elevation', 'ride_avg_speed',
       'ride_cruise_speed', 'ride_max_speed', 'training_window_id',
       'ride_avg_power', 'ride_max_power', 'peak_20min_power'],
      dtype='object')

In [8]:
col_order = ['ride_id','row_count','segment_count','ride_date','start_time','end_time','elapsed_time','ride_elapsed_time',
             'moving_time','ride_moving_time',
             'distance','elapsed_distance','elevation_gain','elapsed_ascent','elevation_loss','elapsed_descent',
             'elapsed_elevation', 'max_speed','ride_max_speed','avg_speed','ride_avg_speed','ride_cruise_speed',
             'avg_power','ride_avg_power','ride_max_power','peak_20min_power','training_window_id',
             'calories','perceived_exertion','simple_exertion','perceived_relative_effort'
            ]

In [9]:
# check that I got everything
[x for x in col_order if x not in df.columns]

[]

In [10]:
df = df[col_order]

In [11]:
df.head()

,ride_id,row_count,segment_count,ride_date,start_time,end_time,elapsed_time,ride_elapsed_time,moving_time,ride_moving_time,distance,elapsed_distance,elevation_gain,elapsed_ascent,elevation_loss,elapsed_descent,elapsed_elevation,max_speed,ride_max_speed,avg_speed,ride_avg_speed,ride_cruise_speed,avg_power,ride_avg_power,ride_max_power,peak_20min_power,training_window_id,calories,perceived_exertion,simple_exertion,perceived_relative_effort
0,2975587283,1352,5,2020-01-02 14:02:00,2020-01-02 14:02:58+00:00,2020-01-02 14:29:32+00:00,1642,1595,1411,1352,5.275440,5.266647,64.165031,137.1458,NaN,138.7863,275.9321,20.132460,20.107674,13.473164,14.045509,14.547075,NaN,116.870855,5.520265e+02,124.782357,0,NaN,7.0,HARD,45.0
1,2992935347,1426,5,2020-01-08 13:20:00,2020-01-08 13:20:26+00:00,2020-01-08 13:49:06+00:00,1728,1721,1472,1426,5.231944,5.167961,151.908747,215.2336,NaN,153.2227,368.4563,31.764548,30.585623,12.807393,13.119808,14.154069,NaN,122.304555,9.702958e+02,131.178797,0,NaN,NaN,NaN,NaN
2,2994399692,1423,7,2020-01-08 22:08:00,2020-01-08 22:08:17+00:00,2020-01-08 22:35:04+00:00,1608,1608,1481,1423,5.294081,5.257609,87.028579,158.4723,NaN,219.4989,377.9712,25.501115,25.544568,12.876376,13.339800,15.443823,NaN,113.161863,1.299650e+03,126.461932,0,NaN,NaN,NaN,NaN
3,3248077156,2580,5,2020-04-02 21:38:00,2020-04-02 21:38:02+00:00,2020-04-02 23:03:45+00:00,5143,5144,2544,2580,6.437404,6.759676,237.698200,329.4124,182.908144,274.6197,604.0321,29.974995,219.457474,9.115003,9.548413,13.495738,NaN,402.495491,2.608934e+05,737.913342,1,NaN,5.0,NORMAL,45.0
4,3255473930,6416,12,2020-04-04 17:23:00,2020-04-04 17:23:43+00:00,2020-04-04 19:59:16+00:00,9348,9334,6356,6416,21.716916,22.730090,346.799121,575.1593,348.110235,576.4717,1151.6310,32.211935,513.399434,12.300812,12.764180,14.009717,NaN,2104.760010,3.328601e+06,121.068376,1,NaN,5.0,NORMAL,114.0

### Save the Data

In [12]:
df.to_csv(file_paths['out'], index=False)